### ISSUE TITLE
libjack-jackd2-dev missing?

### ISSUE THREAD

**Issue by Mduq1201** [Noisk8/InstalandoFoxDot-En-linux#1]
Hi, there.
I'm using Ubuntu 16.04 i386 & SuperCollider 3.9.1. After I run the script, it complained: Jack selected as audio API, but development files not found.
I tried to install the libjack-jackd2-dev, then it no longer complains.

**Comment by Noisk8** [comment]
u can show me  a screenshot? plz

**Comment by Mduq1201** [comment]
Sorry, I didn't take any screenshot and the terminal is already closed.
However, I'll try to reproduce the problem and show you the screenshot in 3 days.
